name: Release for Windows (Single File)

on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch:

jobs:
  build-n-publish:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies and build tools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
        pip install pyinstaller
        pip install pyinstaller-versionfile
        pip install -e .[win32,battery,cookies,ytdl,ai]

    # Step 4: Download mpv-1.dll
    - name: Download mpv-1.dll
      run: |
        choco install curl
        curl -L https://github.com/feeluown/FeelUOwn/releases/download/v3.8/mpv-1.dll -o mpv-1.dll

    # Step 5: Build single-file executable
    - name: Build single-file executable
      run: |
        # Add current working directory to PATH so that mpv-1.dll can be found.
        $env:path += ";."

        # Use PyInstaller to create a single-file executable
        pyinstaller --onefile --windowed --name FeelUOwn feeluown/__main__.py

        # Move the generated executable to the dist directory
        mkdir -p dist
        mv dist/FeelUOwn.exe dist/FeelUOwn-singlefile.exe

    # Step 6: Archive the single-file executable
    - name: Archive single-file executable
      run: |
        ls dist/
        powershell Compress-Archive dist/FeelUOwn-singlefile.exe dist/FeelUOwn-windows-singlefile.zip

    # Step 7: Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FeelUOwn-windows-singlefile.zip
        path: dist/FeelUOwn-windows-singlefile.zip

    # Step 8: Upload to release page
    - name: Upload to release page
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwn-windows-singlefile.zip

    # Step 9: Upload to nightly
    - name: Upload to nightly
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwn-windows-singlefile.zip
        tag_name: nightly
